In [2]:
import pandas as pd
import numpy as np

In [4]:
list1 = [1,2,3,4]
array1 = np.array(list1)
print(array1)

[1 2 3 4]


In [5]:
list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


In [7]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [8]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [9]:
dates = pd.date_range("20130101", periods=6)

dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [12]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ADEF"))
df

A         D         E         F
2013-01-01  1.201998  1.164206  0.548072  1.217990
2013-01-02 -1.322541 -0.428499  0.400263  0.504616
2013-01-03 -0.478399 -1.152594 -2.153487  1.025291
2013-01-04  0.304725  0.794241  1.858771  0.394960
2013-01-05 -0.428865 -0.492652  0.937754  0.249832
2013-01-06  1.620424  2.403433  0.635078  2.248016

In [18]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1.4, index=list(range(4)), dtype="float32"),
        "D": np.array([20] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

df2

A          B    C   D      E    F
0  1.0 2013-01-02  1.4  20   test  foo
1  1.0 2013-01-02  1.4  20  train  foo
2  1.0 2013-01-02  1.4  20   test  foo
3  1.0 2013-01-02  1.4  20  train  foo